### ISSUE TITLE
Incompatibility with NextJS v10.2.0

### ISSUE THREAD

**Issue by iamgenchi** [torusresearch/fetch-node-details#25] opened 2021-05-17 07:58 UTC
Hi Team,

`NextJS v10.2.0` is using `Webpack 5` by default, this library seems to be incompatible with Webpack 5 as it runs into this [error](https://github.com/torusresearch/fetch-node-details/issues/23).

Would you plan to support Webpack 5 or would you need any support from the community to do this?

**Comment by chaitanyapotti** [comment] 2021-05-17 12:22
packages bundled with webpack 4 work perfectly fine with webpack 5 projects. (which is the case with the latest release)
packages bundled with webpack 5 won't work with webpack 4 projects.

Hence, this package is being bundled with webpack 4 now.
Please update to the latest sdk version

I created a sample next.js project and tried this. It seems to be working fine. (Pls update to the latest build of direct web sdk)
If not, pls create a minimal reproducible example with the issue.

I will close this issue once you can confirm this.

**Comment by chaitanyapotti** [comment] 2021-05-19 12:17
Closing this

**Closed by chaitanyapotti** 2021-05-19 12:17 UTC
